### ISSUE TITLE
root template match can be anything besides just "/"

### ISSUE THREAD

**Issue by berenddeboer** [DesignLiquido/xslt-processor#35]
See pull request #34 for more details. Just adds a failing test.

**Comment by leonelsanchesdasilva** [comment]
Hi @berenddeboer. Thanks for the test on this. 

Using your test, I got to find that the evaluation context starts on a `#document` element, which is created above the first element for some reason. That's why this matches:

```<xsl:template match="/">```

But this does not:

```<xsl:template match="/root">```

My next version will have a fix for this, specifically.

**Comment by leonelsanchesdasilva** [comment]
Solved on https://github.com/DesignLiquido/xslt-processor/releases/tag/v1.0.0
